---
humio-core:
  enabled: true
  replicas: 4
  primaryStorage:
    type: remote
    mountPath: /data/humio-data
    logsMountPath: /data/logs
  storageClassName: gp2
  cp-helm-charts:
    cp-zookeeper:
      persistence:
        enabled: false
    cp-kafka:
      persistence:
        enabled: true
        storageClass: gp2
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node_type
            operator: In
            values:
            - humio
humio-fluentbit:
  enabled: true
  es:
    autodiscovery: true
humio-metrics:
  enabled: false
global:
  sharedTokens:
    fluentbit: {kubernetes: in-cluster}
